version: '3'
services:
  server:
    image: node:14
    ports :
      - "80:80"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - database
    networks:
      - db
      - exterior
    command: npm start

  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      - db
      - exterior

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - db
      - exterior

networks:
  exterior:
    internal: false
  db:
    internal: true

